name: "multi_io_model"
backend: "openvino"
max_batch_size: 0
input: [
  {
    name: "input_a"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  },
  {
    name: "input_b"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  }
]
output: [
  {
    name: "out_a"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  },
  {
    name: "out_b"
    data_type: TYPE_FP32
    dims: [ 1, 4 ]
  }
]
instance_group {
  count: 1
  kind: KIND_CPU
}
